### ISSUE TITLE
Update the constants to meet Carla's requirements.

### ISSUE THREAD

**Issue by clockworkbits** [clockworkbits/CarND-Capstone#11]
The self-driving car (Carla) requires some specific rate of updates like in DBW:

> The DBW system on Carla expects messages at this frequency, and will disengage (reverting control back to the driver) if control messages are published at less than 10hz. This is a safety feature on the car intended to return control to the driver if the software system crashes. You are welcome to modify how the dbw_node.py code is structured, but please ensure that control commands are published at 50hz.

Make sure that the project before submission meets the requirements.

Debug constants in `waypoint_updater.py`:
* ~`REFRESH_RATE_HZ = 2` , should be `REFRESH_RATE_HZ =10` **?**~
* `REFRESH_RATE_HZ = 2`, should be `REFRESH_RATE_HZ = 50` 👍 
* ~`UPDATE_MAX_ITER = 50`, should be `UPDATE_MAX_ITER = 1`~
* ~`WAYPOINT_INCREMENT_RATE = 5`, should be `WAYPOINT_INCREMENT_RATE = 1`~
* `DEBUG_MODE = False`, should be `DEBUG_MODE = False` 👍 
* `TL_DETECTOR_ON = False`, should be `TL_DETECTOR_ON = True` 👍 

Debug constants in `tl_detector.py`:
* `DETECTOR_ENABLED = False`, should be `DETECTOR_ENABLED = True` 👍 
* `DEBUG_MODE = False`, should be `DEBUG_MODE = False` 👍 
* `PARKING_LOT_TEST = False`, should be `PARKING_LOT_TEST = False` 👍 

Debug constants in `tl_classifier.py`:
* `SIMULATOR_TRACK = True` , should be `SIMULATOR_TRACK = False` 👍 
* `IMAGE_CAPTURE = False`, should be `IMAGE_CAPTURE = False` 👍 
* ~`DEBUG_MODE= False`, should be `DEBUG_MODE = False`~

Debug constants in `twist_controller.py` : 
* ~`ENABLE_BRAKES = True` , remove and remove the `if/else` conditions but leave the `if` code block related~ not there anymore
* ~`USE_YAW_CONTOLLER = False` remove it and related if/else block in `control()` function , after we decide which controller will be used~
* `USE_YAW_CONTOLLER = False` 👍

**Comment by jodiealaine** [comment]
There is just one discrepancy between the specified constants here and what we have in the #35 (Remove the debug settings for the submission) PR:

Debug constants in waypoint_updater.py:

- Specified in here : REFRESH_RATE_HZ = 2 , should be REFRESH_RATE_HZ =10 ?
- On the PR #35  (now on Master) : REFRESH_RATE_HZ = 50

I believe that the constant value set in the PR is actually the correct value, so we just need to reflect this in this issue. Thus, all is good with the settings for submission 👍

### Final constants for submission:

*waypoint_updater.py:*
`LOOKAHEAD_WPS   = 200`   
`CIRCULAR_WPS    = False`
`REFRESH_RATE_HZ = 50`
`DEBUG_MODE      = False`
`TL_DETECTOR_ON  = True`
`DECELLERATION   = 3`

*tl_detector.py:*
`DETECTOR_ENABLED = True`
`DEBUG_MODE = False` 
`PARKING_LOT_TEST = False`

*tl_classifier.py:*
`SIMULATOR_TRACK = False`
`IMAGE_CAPTURE = False` 
`DEBUG_MODE = False`

*twist_controller.py:*
`GAS_DENSITY = 2.858`
`ONE_MPH = 0.44704`
`USE_YAW_CONTOLLER = False`
