### ISSUE TITLE
Explore the potential use of the low pass filter in the DBW controllers

### ISSUE THREAD

**Issue by clockworkbits** [clockworkbits/CarND-Capstone#15]
The project provides the `lowpass.py` implementation of the Low-pass filter. We should explore it's usage to smooth the way the car drives.

**Comment by anasmatic** [comment]
I don't get this lowpass filter.
I thought if you pass a value to it should apply some top limit filter , right ?

**Comment by jodiealaine** [comment]
Closing this issue as we will not be exploring this option now as part of our team submission.
