### ISSUE TITLE
Erratic driving in the test lot

### ISSUE THREAD

**Issue by clockworkbits** [clockworkbits/CarND-Capstone#18]
The car in the simulator very quickly goes off the path.
The investigation done by @anasmatic :
>  the problem is in `twist_controller.py`
in the initialization of `YawController` I'm using a parameter `self.min_speed`
please replace this with `0`
the car will start steering better , but it needs more improvements
I'll create a new branch and work on that

**Comment by anasmatic** [comment]
I was not able to improve Steering using YawController
So I switched to PID (which is also working fine with the Highway simulator)
Right now I can take the first U turn good, but I got stuck at waypoint 60
total waypoints are 61

https://github.com/clockworkbits/CarND-Capstone/commit/ddf69ae1ac417ddc18577cb7181e45348f36dd42
my waypoint settings : REFRESH_RATE_HZ = 15 , UPDATE_MAX_ITER = 15
