### ISSUE TITLE
Waypoints are not correctly provided after a full cycle for the test lot

### ISSUE THREAD

**Issue by clockworkbits** [clockworkbits/CarND-Capstone#20]
Car is stuck on waypoint 60 of 61
![waypoints-lot-stuck-at-60](https://user-images.githubusercontent.com/7009184/37828186-5c0c54e6-2eee-11e8-9361-253ecf39dea4.jpg)

**Comment by anasmatic** [comment]
@lorenzolucido I did some testing , with LOOKAHEAD_WPS = 2
I noticed that `pure_pursuit_core.cpp` prints : **search waypoint is the last**
and the waypoint where the car stopped (# 60) has no twist linear velocity 
so the car stops at this point is a normal reaction ! 

but I have some doubts that maybe waypoints are flipped , and car should be on waypoint 0 on start , not waypoint 30 ?

this is the result `waypoint_update.py` prints from function `publish_update()`

>[DEBUG] [1521918544.354557]: Next waypoint: 55
[DEBUG] [1521918544.356305]:          info: pose: 
  header: 
    seq: 0
    stamp: 
      secs: 0
      nsecs:         0
    frame_id: ''
  pose: 
    position: 
      x: 11.9502
      y: 15.8813
      z: 0.8892
    orientation: 
      x: 0.0
      y: 0.0
      z: -0.994674830962
      w: 0.103062993602
twist: 
  header: 
    seq: 0
    stamp: 
      secs: 0
      nsecs:         0
    frame_id: ''
  twist: 
    linear: 
      x: 3.31051883809
      y: 0.0
      z: 0.0
    angular: 
      x: 0.0
      y: 0.0
      z: 0.0

>[DEBUG] [1521918544.866195]: Next waypoint: 60
[DEBUG] [1521918544.867719]:          info: pose: 
  header: 
    seq: 0
    stamp: 
      secs: 0
      nsecs:         0
    frame_id: ''
  pose: 
    position: 
      x: 6.6734
      y: 14.4438
      z: 0.5474
    orientation: 
      x: 0.0
      y: 0.0
      z: -0.990348624425
      w: 0.138598708868
twist: 
  header: 
    seq: 0
    stamp: 
      secs: 0
      nsecs:         0
    frame_id: ''
  twist: 
    linear: 
      x: 0.0
      y: 0.0
      z: 0.0
    angular: 
      x: 0.0
      y: 0.0
      z: 0.0

**Comment by anasmatic** [comment]
hot fix, if you want to loop the lot scene , in `waypoint_updater.py` add this code line 
`if 60 in indices : indices.remove(60)`
 to the second line in : 
`next_waypoints_circular()`

**Comment by clockworkbits** [comment]
Can be related to https://github.com/clockworkbits/CarND-Capstone/issues/23

**Comment by anasmatic** [comment]
I have an update :

I was able to restore steering by YawController , which was smoother than PID - as @lorenzolucido  advices -
steps : 
  1.  I commented only one line in *waypoint_updater.py*
in function `search_next_waypoint()`
comment line 200 `self.next_waypoint = 0` at the first or second line of this function

  2. uncomment 1 line and comment 2 lines in *twist_controller.py* 
in function `control()`
uncomment line 47, `steer =  self.yaw_controller.get_steering(args[0],args[1],args[2])`
comment line 48 , `steer_CTE = args[1]-args[3]`
comment line 48 , `steer = self.pid_steer.step(steer_CTE, self.sample_time)`

I have 2 comments on this fix - those 2 scenarios may only occur on my machine - :
  * Highway scene is only working fine when UPDATE_MAX_ITER = 50, or else it will have a very big tail of waypoints
  * Lot scene is only working fine when UPDATE_MAX_ITER = 1, or else it will crash while taking very wide turns
