### ISSUE TITLE
Brake Jerking

### ISSUE THREAD

**Issue by anasmatic** [clockworkbits/CarND-Capstone#30]
car is jerking from speed 2 to zero and back while braking and almost hitting 0 velocity
this is because the current velocity becomes more than the targeted velocity 

this is how function `traffic_cb` @ waypoints_updater.py export new velocities on red traffic lights
> wp[273]target_vel 4.412935
> wp[274]target_vel 4.296341
> wp[275]target_vel 4.057773
> wp[276]target_vel 3.699923
> wp[277]target_vel 3.461359
> wp[278]target_vel 3.342078
> wp[279]target_vel 3.222797
> wp[280]target_vel 2.865167
> wp[281]target_vel 2.626610
> wp[282]target_vel 2.388261
> wp[283]target_vel 2.268985
> wp[284]target_vel 1.911364
> wp[285]target_vel 1.673216
> wp[286]target_vel 1.553943
> wp[287]target_vel 1.315795
> wp[288]target_vel 0.955682
> wp[289]target_vel 0.717337
> wp[290]target_vel 0.598262
> wp[291]target_vel 0.360114

after that , wp **292** is the traffic light and it is set to 0 with all the way points ahead it

the problem happens between waypoints 291 and 292 ,
velocity hits below 0.360114, then rise again to be more than 0.360114 , the decelerate to be below 0.360114 , which makes the car jerks before full stop action.

my recommended solutions are :
- set more waypoints to 0 before the traffic light waypoint.
- or set all waypoints at the stopping distance to 0 , 
in both setuations dbw will handle braking gradually and smoothly
- or change the gradient deceleration ratio to be stronger when we get closer 0

**Comment by clockworkbits** [comment]
I think, if we set all the waypoints at the stopping distance to 0 it may happen that the car will stop way ahead of the traffic lights.

**Comment by anasmatic** [comment]
yes, this will require shortening the stopping distance as well

**Comment by jodiealaine** [comment]
This has been solved by the following: #34 - stay on traffic light until car passes light (instead of stop line)
