### ISSUE TITLE
Car stuck at intersection even traffic light is green

### ISSUE THREAD

**Issue by anasmatic** [clockworkbits/CarND-Capstone#38]
footage of the issue issue was provided with final project result from the grader : 

how to reproduce the issue : 

_slow machine : _
* toggle Camera ON
* Drive the car your self to traffic ligh, make sure it is red and it is detected as red - from debug msgs - 
* now drive after the line on the ground a pit , brake and wait there, 
* look at debug msgs , we will never restore points because camera will detect yellow and grees as red and amber respectively
 
_fast machine :_
* toggle Camera ON
* toggle Autonomous ON
* when car stop at traffic light , toggle Autonomous OFF , and drive yourself to after the line on the ground and before intersection center 
* toggle Autonomous ON again
* wait till traffic light is green , car will not move.

results =========

this image was detected as red light  _tc_image_63_red_0.686.jpg_ 
![tc_image_63_red_0 686](https://user-images.githubusercontent.com/3892671/38687348-0ff5e85e-3ea9-11e8-8bb2-271af3ec0a83.jpg)

this image was detected as yellow light   _tc_image_64_amber_0.365.jpg_
![tc_image_64_amber_0 365](https://user-images.githubusercontent.com/3892671/38687349-103012ae-3ea9-11e8-9e44-b60167d0d862.jpg)

**moving car to right position in intersection is subject of trial and error, but once you got it, you will be able to do it again**
car aprox position : 
![stuck](https://user-images.githubusercontent.com/3892671/38688158-fa24ebcc-3eaa-11e8-88f6-63b1bb39b1fc.jpg)

**Comment by agotterba** [comment]
I've reproduced the failure.  I'll edit tl_detector to report the next traffic light's stop line as soon as the car passes the current light's stopline
