### ISSUE TITLE
[TLD] Build DNN model for traffic light detection

### ISSUE THREAD

**Issue by agotterba** [clockworkbits/CarND-Capstone#7]
Design and build a DNN for detecting traffic lights in an image.  

This should be outside of the ros area- ros only needs to load the model and run inference.

**Comment by jodiealaine** [comment]
Models have been built outside of the project repo. The results of this work are the following trained models which have been added to the repo:

- [Parking Lot - real world DNN model](https://github.com/clockworkbits/CarND-Capstone/tree/add-tld-parking-lot-model)
- [Simulator DNN model](https://github.com/clockworkbits/CarND-Capstone/tree/add-tld-simulator-model)
