### ISSUE TITLE
[TLD] Train DNN for traffic light detection

### ISSUE THREAD

**Issue by agotterba** [clockworkbits/CarND-Capstone#8]
Train the traffic light detection network.  

We can get data from the simulator, the test lot's bag file, or from these sources:

Bosch dataset: https://hci.iwr.uni-heidelberg.de/node/613278, https://github.com/bosch-ros-pkg/bstld68
Viva: http://cvrr.ucsd.edu/vivachallenge/index.php/traffic-light/traffic-light-detection/52

This is split into two parts:

1. Simulator model
2. Parking lot (Carla) model

**Comment by agotterba** [comment]
I was able to run detection on the ros bag file, and am seeing a low rate of detection.  Attached is a selection of images  from one run, along with the log file:

[parking_lot_data.tar.gz](https://github.com/clockworkbits/CarND-Capstone/files/1844101/parking_lot_data.tar.gz)

The images are named:

tc_image_<image_number>_<classification_result>_<detection_score>.jpg

I set the score threshold to 0.5 (I previously had it at 0.65, but that resulted in too few detections).  A score of 0.000 means there was no detection.  Some, such as tc_image_1_green_0.586.jpg are classified incorrectly (in this case, the light is red).  In ic_image_32_green_0.675.jpg, the light is red, and the score is reasonably high.

One thing I'd like to try in tl_classifier.py is cropping out the reflections on the hood of the car.  I'll try that this weekend.

**Comment by jodiealaine** [comment]
Trained models are included in the following approved/merged PR:

- [TLD new parking lot models](https://github.com/clockworkbits/CarND-Capstone/pull/24)
